name: Build and Test

on: push
jobs:
    build-test:
        name: Build and Test Job
        runs-on: ubuntu-16.04
        strategy:
            matrix:
                python-version: [ '3.5.7', '3.6.9', '3.7.5' ]
        steps:
            - uses: actions/checkout@v1
            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                python-version: ${{ matrix.python-version }}
                architecture: x64
            - name: Setup Virtualenv and Build
              shell: bash
              env:
                PARAMETERS_SECRET: ${{ secrets.PARAMETERS_SECRET }}
                another_secret: ${{ secrets.another_secret }}
              run: ./scripts/install_github_workflow.sh
            - name: Tests
              shell: bash
              run: ./scripts/run_github_workflow.sh
